#+title: Dynamic Paper

Manage backgrounds that stay the same or change over the course of the day

* Background Sets
Different wallpaper background are organized into a concept of "Background Sets". You can choose to
show 1 background set, which will change the background. A background set can be =static=, which will
show a single image, or =dynamic=, which will change at different times of the day.

* General Config Options
- =method=: ~string~. Specifies how it should change the background. Acceptable values are:
  + =wallutils= : will change the background using =setwallpaper= from [[https://github.com/xyproto/wallutils][wallutils]]
  + =scrpt= : will execute a user defined
- =sun_poller=: ~string~. Method used to determine the location of the sun in the sky
- =background_config=: ~string~. Location of the file that should be loaded to get information about
background sets
- =method_script=: path to a script that should be used to change the background. *Must* be specified if =method= is =script=.




* Background Set Config Options
**  Static Background Config
=- type=: =static
- =data_directory= : ~string~ representing parent directory that images are stored.
- =images= or =image=: ~list(string)~ or ~string~. List of image names or one single image name that can be
  displayed as the background. If multiple images are specified, will randomly choose one when =show= is called.
- =mode=: ~string~. Display mode. Can be either =center= or =fill=.

The path to the image that will be shown can be found by combining the =data_directory= ad =image= paths:
=data_directory= =/= =image=

** Dynamic Background Config
- =type=: =dynamic=
- =data_directory= : ~string~ representing parent directory that images are stored.
- =images= or =image=: ~list[string]~ or ~string~. List of image names or one single image name that can be
  displayed as the background. If multiple images are specified, will randomly choose one when =show= is called.
- =mode=: ~string~  representing Display Mode. Can be either =center= or =fill=.
- =transition=: ~boolean~ for whether it should interpolate transitions
- =number_transition_steps=: ~int~ for number of steps to transition between backgrounds

The path to the image that will be shown can be found by combining the =data_directory= ad =image= paths:
=data_directory= =/= =image=
